/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "../Driver/Inc/stm32f446xx.h"
#include "stddef.h"
#include "string.h"

GPIO_Handle_t STEP;
TIM_Handle_t PWM2;
static uint32_t pulse = 1;
static uint8_t status = 1;
// 1 = UP and 0 = DOWN
int main(void)
{



	memset(&STEP,0,sizeof(STEP));
	memset(&PWM2,0,sizeof(PWM2));
	/*Always initiate clock first before data line*/
	// PA5 ALternate 1 TIM2_CH1
	STEP.pGPIOx = pGPIOA;
	STEP.GPIO_PinConfig.GPIO_PinMode= GPIO_MODE_ALTF;
	STEP.GPIO_PinConfig.GPIO_PinAltFunMode = 1;
	STEP.GPIO_PinConfig.GPIO_PinOPType = GPIO_OUTPUT_TYPE_PP;
	STEP.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_NO_PUPD;
	STEP.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	STEP.GPIO_PinConfig.GPIO_PinNumber = 5;

	GPIO_Init(&STEP);

	PWM2.pTIMx = pTIM2;
	PWM2.TIMx_PinConfig.TIM_Prescaler = 16;
	PWM2.TIMx_PinConfig.TIM_CountDir = UPWARDS;
	PWM2.TIMx_PinConfig.TIM_Channel = TIMx_CH1;
	PWM2.TIMx_PinConfig.TIM_Mode = TIMx_MODE_COMPARE;
	PWM2.TIMx_PinConfig.TIM_CMP_Mode = TIMx_COMPARE_MODE_PWM1;
	PWM2.TIMx_PinConfig.TIM_ARR = 1000;
	PWM2.TIMx_PinConfig.TIM_CCR = 50;

	TIM_Init(&PWM2);
	TIM_InterruptEnable(&PWM2,ENABLE);
	TIM_IRQInterruptConfig(IRQ_NO_TIM2,ENABLE);
    /* Loop forever */
	for(;;){


	}
}

//void TIM2_IRQHandler(void){
//    // 1. Clear interrupt flag
//	PWM2.pTIMx->SR &= ~(1 << TIM_SR_UIF_POS);  // Clear update interrupt flag
//    // 2. Update CCR register to change pulse width (duty cycle) or timing
//	if(status == 1) pulse += 1;
//	else  pulse -= 1;
//
//    if (pulse >= PWM2.pTIMx->ARR){
//
//    	status *= -1;
//    }
//    PWM2.pTIMx->CCR1 = pulse;
//
//}
